### ISSUE TITLE
Issue when building component

### ISSUE THREAD

**Issue by ivanji** [bbc/react-transcript-editor#105]
After running build:component and importing this package as a local module to a create-react-app app, my app fails to compile and I get the following error after I try to import it as 
```import { TranscriptEditor } from '../libs/TranscriptEditor';```

/src/libs/TranscriptEditor/TranscriptEditor/Settings/Shortcuts.js
  Line 1:    Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:  Expected an assignment or function call and instead saw an expression  no-unused-expressions

I've been going around in circles about this issue.

I've removed a bunch of features, hence the need to use a local module instead. I've been doing dev using npm link and building component from the editor dev project but once built I'm failing to import it.

Any guidance would be appreciated. Thanks!

**Comment by pietrop** [comment]
Hi @ivanji, 
Happy to help, but since you said you removed some features, it might be useful to see the code if possible, as that might be make it easier to identify what might be going wrong?

A few things that come to mind

1. Did you remove the `Shortcuts` in your version?

2. Do you still have [this line in `/src/lib/TranscriptEditor/MediaPlayer/index.js#L474`](https://github.com/bbc/react-transcript-editor/blob/master/src/lib/TranscriptEditor/MediaPlayer/index.js#L474)?

```js
export default hotkeys(MediaPlayer);
```

3. [`no-unused-expressions`](https://eslint.org/docs/rules/no-unused-expressions) seems to be referring to a linting rule? Do you have that linting rule in your parent project?

---

Out of curiosity, what features did you remove? 

it be interesting to learn more about your use case, as with @chrishutchinson @jamesdools we are considering what could be a good way to refactor the internal components of `TranscriptEditor` to make it easier to customise and reuse parts of it.

**Comment by ivanji** [comment]
Thanks for your response @pietrop  

I found out what the issue was. I just shouldn't used the built component in a dev env, so I continued using the linked component instead. It was just the wrong approach.

I just removed minor features, nothing worth mentioning :)

**Comment by pietrop** [comment]
Ok great, glad that worked out for you :)
