### ISSUE TITLE
Support for AWS Transcribe Speaker Detection

### ISSUE THREAD

**Issue by philmcmahon** [bbc/react-transcript-editor#127]
**Is your feature request related to a problem? Please describe.**
Currently the AWS Transcribe adaptor doesn't pick up the AWS speaker detection stuff - each line gets listed as a separate speaker. We're looking into doing trasnscription stuff at the guardian at the moment and I heard about this tool from Rich Beddington in the editorial tools team here. Speaker detection for AWS would be a nice feature so I was thinking of having a go at adding it. 

**Describe the solution you'd like**
Text grouped by speaker in the transcript, rather than each line listed as TBC 0. The data for this appears to already be available in the json output by AWS so it should be achievable.

**Describe alternatives you've considered**
Nothing as yet.

**Additional context**
I've got some time next week to work on this, any suggestions appreciated - do you think this is worth doing?

**Comment by pietrop** [comment]
👋  @philmcmahon, Thanks for reaching out, I had also left a message on your https://github.com/guardian/transcribe-tool/issues/1 😄 

I think this is worth doing, and yes, you can see in this PR https://github.com/bbc/react-transcript-editor/pull/120 that the speaker segmentation was left for a later stage.

At the moment me and @jamesdools are addressing this issue https://github.com/bbc/react-transcript-editor/issues/109 following @chrishutchinson PR example https://github.com/bbc/react-transcript-editor/pull/122 to make the codebase more modular, using a monorepo with storybook.

There's a [Guide: How to Create an Adapter](https://github.com/bbc/react-transcript-editor/blob/master/docs/guides/adapters.md) you can have a look at, but any questions feel free to reach out.

In the current master setup you can find the adapters in `src/lib/Util/adapters/` as explained in the guide above. 

In the monorepo/storybook refactor, it will end up somewhere inside the `packages` folder. 

But because the adapters are pretty self contained, you could get started in the current setup and then move it later if we are done with the storybook PR before then, if that makes sense. And we can always help out if it gets confusing.

**Comment by philmcmahon** [comment]
Thanks @pietrop - I've left it with the current setup for now as it's just a couple of files with some fixtures so should be fairly easy to move.

**Comment by pietrop** [comment]
Thanks @philmcmahon I've also added it to the repo refactor PR https://github.com/bbc/react-transcript-editor/pull/135 so that it shouldn't be effected by that, when that's ready for merge
