### ISSUE TITLE
Support to Google Speech To Text transcription format

### ISSUE THREAD

**Issue by eyal13579** [bbc/react-transcript-editor#152]
any plans to support Google?

**Comment by pietrop** [comment]
Hi @eyal13579 , 
At the moment we have been relying on open source contributors to create the adapters they might need, and [made a guide to help with the process](https://github.com/bbc/react-transcript-editor/blob/master/docs/guides/adapters.md). As we are only using the BBC Kaldi in our projects.

If you are interested in creating a Google STT one, and need any help to setup a PR let me know.

**Comment by sshniro** [comment]
Hi @pietrop , I'm familiar with Google STT and would love  to contribute to this development. I have gone through the helper docs. I have a small clarification regarding the which approach to take. Google STT provides speaker diarization as a beta feature, so is it okay if I use the beta results for creating the sample json ?

**Comment by pietrop** [comment]
Hi @sshniro, that's awesome, thanks! 

re-speaker info, sounds good to use the  beta feature for  Google STT speaker diarization.

We have been using a flexible approach in the current module, because a lot of these STT have those optional attributes, so didn't want to impose them as defaults. 

You can see in the other modules, that we check if the attribute is available, if it is we break the paragraph down based on the speaker diarization, if it isn't we break the paragraphs down based on punctuation, and add place holder names to the speaker labels. The user can then change the size of the paragraphs and speaker labels in the UI. 

for example you can see in the `/packages/stt-adapters/bbc-kaldi` we check if the attribute is present in the json ([`/packages/stt-adapters/bbc-kaldi/index.js#L57`](https://github.com/bbc/react-transcript-editor/blob/master/packages/stt-adapters/bbc-kaldi/index.js#L57)) and then we either do `groupWordsInParagraphs` (in[`/packages/stt-adapters/bbc-kaldi/index.js#L15`](https://github.com/bbc/react-transcript-editor/blob/master/packages/stt-adapters/bbc-kaldi/index.js#L15) ) or `groupWordsInParagraphsBySpeakers`( in[`/packages/stt-adapters/bbc-kaldi/group-words-by-speakers.js`](https://github.com/bbc/react-transcript-editor/blob/master/packages/stt-adapters/bbc-kaldi/group-words-by-speakers.js))

I think it be good to add support for both, creating paragraph based on speaker label as well as on punctuation, as a fallback if speaker labels are not provided. However if you want to priorities the speaker labels, and leave the punctuation one for a separate PR that's also fine.

Let me know if you have any questions.

**Comment by sshniro** [comment]
Hi @pietrop I have created a PR for GCP to Draft JS conversion , The PR does not cover speaker diarization. I will send another PR with the segmentation soon.

**Comment by pietrop** [comment]
closing as addressed by @sshniro  in PR https://github.com/bbc/react-transcript-editor/pull/167
