### ISSUE TITLE
edit able not work i can not edit text

### ISSUE THREAD

**Issue by dash7ou** [bbc/react-transcript-editor#245]
isEditable={true} but i can not edit text in browser?!

**Comment by pietrop** [comment]
@dash7ou did you figure it out?

**Comment by dash7ou** [comment]
no, but no one reply to me?
this is my code:-
        <TranscriptEditor
          transcriptData={transcribeData.versionData.text_json}
          mediaUrl={`${process.env.REACT_APP_S3_BACKET}/${process.env.REACT_APP_S3_ENV}${transcribeData.vedio}`}
          isEditable={true}
          sttJsonType={transcribeData.versionData.text_json.hasOwnProperty("jobName") ? "amazontranscribe" : "draftjs"}
          mediaType={transcribeData.mimeType}
          handleAutoSaveChanges={handleAutoSaveChanges}
          autoSaveContentType={"draftjs"}
        />

but edit text not work edit owner work perfect but transcript text not work.

**Comment by pietrop** [comment]
What version of `TranscriptEditor` are you using?
I couldn't reproduce the issue [in the storybook demo](https://bbc.github.io/react-transcript-editor/?path=/story/demo--default) (by checking and unchecking the "Text Is Editable" option)

**Comment by dash7ou** [comment]
this is TranscriptEditor ^1.4.1-alpha.8 version I am  using now

**Comment by dash7ou** [comment]
i know no problem in the demo in the storybook but I add isEditable={true} I think it shows working right?

**Comment by pietrop** [comment]
Yes, correct, I think there was a problem with one of the alpha releases.
see this issue https://github.com/bbc/react-transcript-editor/issues/237  and this comment https://github.com/bbc/react-transcript-editor/issues/237#issuecomment-642528651

@jamesdools will be able to confirm (or push an update so that the latest release is a working one?) 

For now, I'd revert back to a non alpha release eg `1.4.1`, if that makes sense?

**Comment by dash7ou** [comment]
ok thanks for the help 3>
