### ISSUE TITLE
Find a sensible combination for Keyboard shortcuts (that does not interfere with defaults)

### ISSUE THREAD

**Issue by pietrop** [bbc/react-transcript-editor#78]
Following up from https://github.com/bbc/react-transcript-editor/issues/75  and https://github.com/bbc/react-transcript-editor/issues/77

it's clear that we need to find sensible combinations for Keyboard shortcuts, that does not interfere with browsers and OS defaults, tested in text editor area to be used along side typing etc..

Suggestions welcome

**Comment by pietrop** [comment]
options suggested by @bevand10 

play media 		`alt` + `space`
play media 		`alt` + `k`  
fast forward		`alt` + `l` // change to  5 sec]
rewind 			`alt` +` j	// change to 5 sec

playback rate decrease	`alt`+ `-`
playback rate increase	`alt`+ `+`

Roll Back		          `alt` +`r`
set current time	  `alt` + `t`

---

Partially Inspired by video editing keyboards

![jkl](https://user-images.githubusercontent.com/4661975/51328180-b52d2100-1a6a-11e9-999f-e7f94aa86e33.png)

in context 
![slack-imgs](https://user-images.githubusercontent.com/4661975/51328175-b1999a00-1a6a-11e9-8296-c646908b8d90.jpg)

**Comment by pietrop** [comment]
Addressed in this PR  https://github.com/bbc/react-transcript-editor/pull/79

**Comment by ranaharoni** [comment]
But we have to keep in mind what this project is all about. It is an editor, and the only reason for which it should have playback shortcuts is to make the task of writing/correcting transcripts easier.

So, in conclusion, unless it's made mostly for Final-cut users in mind (or any other editor), we have to make sure it acts as an editor first and a video-player second, therefore, in my opinion, we should stay away from any combo that might interfere with any *normal situation* in a typing experience. Having that in mind, it makes sense to try to stay away from`shift` and `alt` keys, since these only keys that act as a modifier to produce a different character.

Why not [CTRL/CMD](https://en.wikipedia.org/wiki/Control_key)? According to Wikipedia 

> Control key is a modifier key which, when pressed in conjunction with another key, performs a special **operation**...

There's even a [list of commands](https://en.wikipedia.org/wiki/Control_key#Table_of_examples) we can easily discard, and some marked as "undefined or rarely used"

What do you think?
