### ISSUE TITLE
Element ref was specified as a string (timedTextEditor) but no owner was set.

### ISSUE THREAD

**Issue by ivanji** [bbc/react-transcript-editor#96]
**Describe the bug**

I'm playing around with this awesome editor, and in one of my first tests was to import it into an existing project. I immediately got the following error: 

Element ref was specified as a string (timedTextEditor) but no owner was set. This could happen for one of the following reasons:
1. You may be adding a ref to a function component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded
See https://fb.me/react-refs-must-have-owner for more information

I removed  ref={ 'timedTextEditor' } within lib/TranscriptTextEditor/ line 274 and the error went away. Not sure if there's another underlying issue or if that's the correct solution.

**To Reproduce**
Import it into a new React Project

**Expected behavior**
No errors :)

**Comment by pietrop** [comment]
Thanks @ivanji ! Will have a closer look at this, and circle back with any questions.

**Comment by pietrop** [comment]
Thanks @ivanji for flagging this!
ok so, simply removing [` ref={ 'timedTextEditor' }` at `src/lib/TranscriptEditor/index.js#L279`](https://github.com/bbc/react-transcript-editor/blob/master/src/lib/TranscriptEditor/index.js#L279) it's not a solution as it breaks the local save. (if you comment it out and click on the 💾  icon and the app will crash)

one option would be to refactor the code to remove refs. 

But as that might be time consuming for now, I'd like to roll out that it's not the most likely which is the 3rd issue - `Multiple copies of React`.

> You have multiple (conflicting) copies of React loaded (eg. **due to a misconfigured npm dependency**)

https://reactjs.org/warnings/refs-must-have-owner.html#multiple-copies-of-react

I think this is the most likely. 

> Bower does a good job of deduplicating dependencies, but npm does not. If you aren’t doing anything (fancy) with refs, there is a good chance that the problem is not with your refs, but rather an issue with having multiple copies of React loaded into your project. Sometimes, when you pull in a third-party module via npm, you will get a duplicate copy of the dependency library, and this can create problems.
>
>If you are using npm… npm ls or npm ls react might help illuminate.

Can you try and in this order do
- [ ]  uncomment the `timedTextEditor` ref in `TranscriptTextEditor` 
- [ ] `rm -rf node_modules`
- [ ]  `rm -rf package-lock.json`
- [ ] `npm install` 
- [ ] and see what happens when you do `npm start`

Let me know what error comes up :)

**Comment by pietrop** [comment]
@jamesdools also pointed out it could also be related to this [`Warning about legacy string ref API usage`](https://reactjs.org/docs/strict-mode.html#warning-about-legacy-string-ref-api-usage)

In which case might be good to do a PR to change all the refs in the project.

**Comment by pietrop** [comment]
PR refactoring refs https://github.com/bbc/react-transcript-editor/pull/99

**Comment by ivanji** [comment]
Thanks @pietrop - I tested with your changes to the TranscriptEditor/index.js (recommended by @jamesdools)  and they seem to have fixed this issue.
